return {
	"chips",
	"I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
	"Why can't a bicycle stand on its own? It's two-tired.",
	"I was wondering why the baseball was getting bigger. Then it hit me.",
	"monke",
	"open the noor.",
	"yes",
	"Peanut butter",
	"chicken sandwich",
	"baller",
	"C H I C K E N  S A N D W I C H 🥪",
	"peanut butter jelly bean",
	"BEANZ WATHEFUUUUUUUU-",
	"mrbeaaaaaast",
	"sus",
	"what the dog doing",
	"whopper whopper whopper whopper juniur double tripple whopper",
	"Did you know, if you divide 10 by 7, you will get a number with infinity decimals?",
	"what the dog doing?",
	"Damn I messed up, we gotta got blad.",
	"I regret nothing."
}
